### ISSUE TITLE
Value of onConflict must be one of OnConflictStrategy

### ISSUE THREAD

**Issue by AbiMulLyA** [Amir-P/flat#25]
Hi.. thanks for forking the floor plugin.. could u fix this one?.. this also issue on floor when I run build_runner command
This is related issue on floor : https://github.com/vitusortner/floor/issues/641

![image](https://user-images.githubusercontent.com/42445812/171586980-8f96acf2-29f1-4fb6-8071-6da321d7ee71.png)

**Comment by Amir-P** [comment]
It should be fixed in the latest release. @AbiMulLyA 

```yaml
dependencies:
  flat_orm: ^1.5.1+1

dev_dependencies:
  flat_generator: ^1.6.1+1
```
